CREATE TABLE employee_details_dummy (
  id int NOT NULL AUTO_INCREMENT,
  branch varchar(255) DEFAULT NULL,
  country varchar(255) DEFAULT NULL,
  designation varchar(255) DEFAULT NULL,
  dob varchar(255) DEFAULT NULL,
  gender varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  phone varchar(255) DEFAULT NULL,
  salary double DEFAULT NULL,
  dept_name varchar(255) DEFAULT NULL,
  emp_no varchar(255) NOT NULL,
  first_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  email_id varchar(255) DEFAULT NULL,
  employee_type varchar(255) DEFAULT NULL,
  status bit(1) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY emp_no_UNIQUE (emp_no),
)

-----------------------------------------------
INSERT INTO demo.employee_details
(id,
branch,
country,
deptName,
designation,
dop,
email,
empNo,
firstName,
gender,
lastName,
password,
phone,
salary,
dept_name,
emp_no,
first_name,
last_name,
email_id,
employee_type,
status)
VALUES
(<{id: }>,
<{branch: }>,
<{country: }>,
<{deptName: }>,
<{designation: }>,
<{dop: }>,
<{email: }>,
<{firstName: }>,
<{gender: }>,
<{lastName: }>,
<{password: }>,
<{phone: }>,
<{salary: }>,
<{dept_name: }>,
<{emp_no: }>,
<{first_name: }>,
<{last_name: }>,
<{email_id: }>,
<{employee_type: }>,
<{status: }>);
------------------------------------------------------------------
UPDATE demo.employee_details
SET
id = <{id: }>,
branch = <{branch: }>,
country = <{country: }>,
deptName = <{deptName: }>,
designation = <{designation: }>,
dop = <{dop: }>,
email = <{email: }>,
firstName = <{firstName: }>,
gender = <{gender: }>,
lastName = <{lastName: }>,
password = <{password: }>,
phone = <{phone: }>,
salary = <{salary: }>,
dept_name = <{dept_name: }>,
emp_no = <{emp_no: }>,
first_name = <{first_name: }>,
last_name = <{last_name: }>,
email_id = <{email_id: }>,
employee_type = <{employee_type: }>,
status = <{status: }>
WHERE id = <{expr}>;

